---
- hosts: all
  sudo: yes
  vars:
    newrelic_license_key: test
    pgbouncer_command_db:
  vars_files:
    - ./defaults/main.yml
  handlers:
    - include: ./handlers/main.yml
  tasks:
    - apt: pkg=supervisor state=present
    - include: ./tasks/main.yml
    - command: service pgbouncer restart
    - include: ./tasks/ops.yml pgbouncer_command=stats
    - include: ./tasks/ops.yml pgbouncer_command=pause
    - include: ./tasks/ops.yml pgbouncer_command=resume
