---
- hosts: all
  sudo: yes
  vars:
    newrelic_license_key: test
  vars_files:
    - ./defaults/main.yml
  handlers:
    - include: ./handlers/main.yml
  tasks:
    - apt: pkg=supervisor state=present
    - include: ./tasks/main.yml
#    - shell: netstat -anplt | grep 6432 | wc -l
#      register: netstat
#    - assert:
#      that:
#        - "'0' != netstat.stdout"
#    - include: ./tasks/ops.yml pgbouncer_command=stats
#    - include: ./tasks/ops.yml pgbouncer_command=pause
#    - include: ./tasks/ops.yml pgbouncer_command=resume
