---

- apt: pkg=libpq-dev state=present
  with_items:
    - libpq-dev
    - supervisor
- pip: name=newrelic-plugin-agent
- pip: name=newrelic-plugin-agent[pgbouncer]
- template: src=pgbouncer/newrelic.ini.j2 dest=/etc/newrelic/newrelic-plugin-agent.cfg owner=newrelic group=newrelic mode=0440
- file: path=/var/log/newrelic state=directory owner=newrelic group=newrelic
- file: path=/var/run/newrelic state=directory owner=newrelic group=newrelic

# TODO: use supervisor to get this thing up and running
