---

- apt: pkg={{ item }} state=present
  with_items:
    - libpq-dev
    - supervisor
- user: name=newrelic
- pip: name=newrelic-plugin-agent
- pip: name=newrelic-plugin-agent[pgbouncer]
# HACK: it's in the list of requirements but does not work
- easy_install: name=requests
- file: path=/etc/newrelic state=directory owner=newrelic group=newrelic
- file: path=/var/log/newrelic state=directory owner=newrelic group=newrelic recurse=true
- file: path=/var/run/newrelic state=directory owner=newrelic group=newrelic
- template: src=pgbouncer/newrelic.ini.j2 dest=/etc/newrelic/newrelic-plugin-agent.cfg owner=newrelic group=newrelic mode=0440
- template: src=pgbouncer/supervisor.newrelic.j2 dest=/etc/supervisor/conf.d/newrelic-plugin-agent.conf
  notify:
    - reload supervisord
