---
- name: restart pgbouncer
  service: name=pgbouncer state=restarted

- name: reload pgbouncer
  service: name=pgbouncer state=reloaded

- name: restart monit
  service: name=monit state=restarted
