---
- name: restart pgbouncer
  service: name=pgbouncer state=restarted

- name: reload pgbouncer
  service: name=pgbouncer state=reloaded

- name: restart monit
  service: name=monit state=restarted

- name: reload supervisord
  command: supervisorctl reload

- name: reload logrotate
  command: logrotate -s /var/lib/logrotate.status /etc/logrotate.conf
